### ISSUE TITLE
es6.6 同步有问题

### ISSUE THREAD

**Issue by mklabcn** [m358807551/mysqlsmom#17]
2019-07-08 17:31:42,149 root         INFO     {"status": "\u0001", "lang": -1, "update_time": "2019-07-08 17:23:37", "github": null, "star": 5, "descr": "api", "tags": "[\"api\", \"springboot\"]", "favicon": "/favicon/spring.png", "title": "SpringBoot", "show": "\u0001", "gitee": null, "link": "https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/api/", "insert_time": "2016-11-28 16:14:01", "indexed": "springboot", "sorted": 1110, "_id": 423, "type": 100026, "id": 423}
2019-07-08 17:31:42,161 elasticsearch INFO     POST http://localhost:9200/_bulk [status:200 request:0.011s]
2019-07-08 17:31:42,164 apscheduler.executors.default ERROR    Job "do_one_task (trigger: interval[0:01:00], next run at: 2019-07-08 17:32:42 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/lib/python2.7/site-packages/mysqlsmom/mysqlsmom.py", line 339, in do_one_task
    to_dest.upload_docs()
  File "/usr/lib/python2.7/site-packages/mysqlsmom/mysqlsmom.py", line 141, in upload_docs
    raise e
BulkIndexError: (u'1 document(s) failed to index.', [{u'update': {u'status': 400, u'_type': u'open', u'_index': u'admin', u'error': {u'caused_by': {u'reason': u'Failed to parse value [\x01] as only [true] or [false] are allowed.', u'type': u'illegal_argument_exception'}, u'reason': u'failed to parse field [show] of type [boolean]', u'type': u'mapper_parsing_exception'}, u'_id': u'423', u'data': {'doc': {u'status': '\x01', u'lang': -1, u'update_time': datetime.datetime(2019, 7, 8, 17, 23, 37), u'github': None, u'star': 5, u'descr': u'api', u'tags': u'["api", "springboot"]', u'favicon': u'/favicon/spring.png', u'title': u'SpringBoot', u'show': '\x01', u'gitee': None, u'link': u'https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/api/', u'insert_time': datetime.datetime(2016, 11, 28, 16, 14, 1), u'indexed': u'springboot', u'sorted': 1110, u'type': 100026, u'id': 423}, 'doc_as_upsert': True}}}])
^C
Aborted!

**Comment by mklabcn** [comment]
STREAM = "CRON"

# 修改数据库连接
CONNECTION = {
    'host': 'localhost',
    'port': 3306,
    'user': 'admin',
    'passwd': 'xxxx'
}

# redis存储上次同步时间等信息
REDIS = {
    "host": "127.0.0.1",
    "port": 6379,
    "db": 0,
    "password": "xxxxx",  # 不需要密码则注释或删掉该行
}

# 一次同步 BULK_SIZE 条数据到elasticsearch，不设置该配置项默认为1
BULK_SIZE = 5000

# 修改elasticsearch节点
NODES = [{"host": "localhost", "port": 9200}]

TASKS = [
    {
        "stream": {
            "database": "admin",  # 在此数据库执行sql语句
            "sql": "SELECT * FROM open WHERE update_time >= ?",  # 将该sql语句选中的数据同步到 elasticsearch
            "seconds": 60,  # 每隔 seconds 秒同步一次,
            "init_time": "2019-07-08 00:00:00"  # 只有第一次同步会加载
        },
        "jobs": [
            {
                "pipeline": [
                    {"set_id": {"field": "id"}}  # 默认设置 id字段的值 为elasticsearch中的文档id
                ],
                "dest": {
                    "es": {
                        "action": "upsert",
                        "index": "admin",   # 设置 index
                        "type": "open"          # 设置 type

                    }
                }
            }
        ]
    }
]

**Comment by m358807551** [comment]
![image](https://user-images.githubusercontent.com/14256423/60801068-e6301800-a1a8-11e9-9bcf-edcb3d30293b.png)
看起来 有个布尔类型的字段 [show] 存了个 '\x01'，既不是true也不是false，所以出错了

**Comment by mklabcn** [comment]
首先感觉您能从百忙中解答疑问

个人觉得可能是查询结果转换问题
show字段定义
`status` bit(1) NOT NULL DEFAULT b'1'
show字段值 1

binlog同步字段对应不上
2019-07-08 19:20:41,657 root         INFO     {"status": 100026, "lang": "/favicon/spring.png", "update_time": "2019-07-08 17:23:37", "github": ["api", "springboot"], "star": -1, "descr": 423, "tags": 1110, "favicon": "SpringBoot", "title": 5, "show": "1", "gitee": "springboot", "link": "api", "insert_time": null, "indexed": null, "sorted": "1", "_id": "https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/api/", "type": "2016-11-28 16:14:01", "id": "https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/api/"}

"id": "https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/api/"  id应为423
"descr": 423  descr应为springboot
