### ISSUE TITLE
elasticsearch 有鉴权，如何配置

### ISSUE THREAD

**Issue by heqin5136** [m358807551/mysqlsmom#23]
遇到ES有鉴权的时候，会报错
`2019-12-10 16:54:19,241 elasticsearch WARNING  Undecodable raw error response from server: No JSON object could be decoded: line 1 column 0 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/mom", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mysqlsmom/mysqlsmom.py", line 416, in run
    handle_init_stream(config_)
  File "/usr/local/lib/python2.7/dist-packages/mysqlsmom/mysqlsmom.py", line 193, in handle_init_stream
    to_dest.upload_docs()
  File "/usr/local/lib/python2.7/dist-packages/mysqlsmom/mysqlsmom.py", line 137, in upload_docs
    helpers.bulk(es, self.docs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/actions.py", line 300, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/actions.py", line 230, in streaming_bulk
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/actions.py", line 116, in _process_bulk_chunk
    raise e
elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, u'Unauthorized')`

模版配置是：
`NODES= [{"host": "10.10.10.10", "port": 8080}]`

鉴权后修改成为如下即可：
`NODES = ["http://user:passwd@10.10.10.10:8080"]`

**Comment by m358807551** [comment]
对不起，不支持鉴权..
