### ISSUE TITLE
mysqlsmom 线程报错

### ISSUE THREAD

**Issue by heidan123** [m358807551/mysqlsmom#24]
`[root@03AF15-A14 video]# mom run -c cron_config.py
2020-03-31 12:38:00,710 apscheduler.scheduler INFO     Adding job tentatively -- it will be properly scheduled when the scheduler starts
2020-03-31 12:38:00,711 apscheduler.scheduler INFO     Added job "do_one_task" to job store "default"
2020-03-31 12:38:00,711 apscheduler.scheduler INFO     Scheduler started
2020-03-31 12:38:00,712 apscheduler.executors.default INFO     Running job "do_one_task (trigger: interval[0:00:10], next run at: 2020-03-31 12:38:00 CST)" (scheduled at 2020-03-31 12:38:00.617124+08:00)
2020-03-31 12:38:01,113 apscheduler.executors.default ERROR    Job "do_one_task (trigger: interval[0:00:10], next run at: 2020-03-31 12:38:10 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/lib/python2.7/site-packages/mysqlsmom/mysqlsmom.py", line 321, in do_one_task
    query = MyModel.raw(task["stream"]["sql"].replace("?", "%s"), (last_start_time,)).dicts().iterator()
  File "/usr/lib/python2.7/site-packages/peewee.py", line 1637, in iterator
    return iter(self.execute(database).iterator())
  File "/usr/lib/python2.7/site-packages/peewee.py", line 1560, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/peewee.py", line 1631, in execute
    return self._execute(database)
  File "/usr/lib/python2.7/site-packages/peewee.py", line 1680, in _execute
    cursor = database.execute(self)
  File "/usr/lib/python2.7/site-packages/peewee.py", line 2638, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/lib/python2.7/site-packages/peewee.py", line 2632, in execute_sql
    self.commit()
  File "/usr/lib/python2.7/site-packages/peewee.py", line 2424, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/lib/python2.7/site-packages/peewee.py", line 2625, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1073, in read
    self._read_result_packet(first_packet)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1143, in _read_result_packet
    self._read_rowdata_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1177, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 670, in _read_packet
    % (packet_number, self._next_seq_id))
InternalError: Packet sequence number wrong - got 1 expected 16
`
怎么解决？

**Comment by heidan123** [comment]
![微信截图_20200331124200](https://user-images.githubusercontent.com/37107409/77987678-0dd59a80-734d-11ea-9dde-d87c76515df7.png)

**Comment by m358807551** [comment]
啊这看起起来是多线程的问题.. 

怀疑是不是把同步一次时间间隔设置的太小了，比如是不是设置的只有几秒钟，对实时性要求不高的话，设置成半分钟或者1分钟试试？

不过杀死进程重启应该会暂时解决这个问题.
