### ISSUE TITLE
当在MySQL中的id为字符串时会报错

### ISSUE THREAD

**Issue by gysan** [m358807551/mysqlsmom#3]
Traceback (most recent call last):
  File "mysqlsmom.py", line 213, in <module>
    handle_init_stream(config_module)
  File "mysqlsmom.py", line 113, in handle_init_stream
    for row in query:
  File "/data/anaconda3/lib/python3.6/site-packages/peewee.py", line 3672, in iterator
    yield self.iterate(False)
  File "/data/anaconda3/lib/python3.6/site-packages/peewee.py", line 3660, in iterate
    result = self.process_row(row)
  File "/data/anaconda3/lib/python3.6/site-packages/peewee.py", line 6348, in process_row
    result[attr] = converters[i](row[i])
  File "/data/anaconda3/lib/python3.6/site-packages/peewee.py", line 3896, in python_value
    return value if value is None else self.adapt(value)
ValueError: invalid literal for int() with base 10: 'stff01'

**Comment by m358807551** [comment]
感谢指出，已修复。
需要在配置文件里添加一行：
```
 "stream": {
            "database": "test_db", 
            "sql": "select * from my_person",
            "pk": {"field": "id", "type": "char"}  # 主键id的类型是字符串
 }
```

**Comment by m358807551** [comment]
1baf455b20b89ac0afc7e2ded272b35bcc35225a [bugfix] Mysql的id字段类型不为整数时，同步会出错。
