### ISSUE TITLE
TypeError: 'dict_items' object does not support indexing

### ISSUE THREAD

**Issue by gysan** [m358807551/mysqlsmom#4]
Traceback (most recent call last):
  File "mysqlsmom.py", line 223, in <module>
    handle_init_stream(config_module)
  File "mysqlsmom.py", line 131, in handle_init_stream
    rows = do_pipeline(job["pipeline"], event["values"])
  File "mysqlsmom.py", line 65, in do_pipeline
    func_name, kwargs = line.items()[0]
TypeError: 'dict_items' object does not support indexing

**Comment by m358807551** [comment]
能把 example_init.py 里的 Tasks部分贴一下吗，如果需要的话加我微信、QQ:358807551

**Comment by m358807551** [comment]
请用Python2版本，稍后加入对Python3的支持。
