### ISSUE TITLE
执行 python mysqlsmom.py config/example_cron.py 报错

### ISSUE THREAD

**Issue by just3019** [m358807551/mysqlsmom#5]
错误
```
Traceback (most recent call last):
  File "mysqlsmom.py", line 357, in <module>
    handle_cron_stream(config_module)
  File "mysqlsmom.py", line 324, in handle_cron_stream
    scheduler = BlockingScheduler()
  File "/data/containers/mysqlsmom/.env/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 83, in __init__
    self.configure(gconfig, **options)
  File "/data/containers/mysqlsmom/.env/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 122, in configure
    self._configure(config)
  File "/data/containers/mysqlsmom/.env/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 691, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/data/containers/mysqlsmom/.env/lib/python2.7/site-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/data/containers/mysqlsmom/.env/lib/python2.7/site-packages/tzlocal/unix.py", line 56, in _get_localzone
    with open(tzpath, 'rb') as tzfile:
IOError: [Errno 21] Is a directory: '/etc/timezone'
```

```
配置：
# 修改数据库连接
CONNECTION = {
    'host': '127.0.0.1',
    'port': 3306,
    'user': 'root',
    'passwd': ''
}

# redis存储上次同步时间等信息
REDIS = {
    "host": "192.168.1.240",
    "port": 6379,
    "db": 0,
    "password": "",  # 不需要密码则注释或删掉该行
}

# 一次同步 BULK_SIZE 条数据到elasticsearch，不设置该配置项默认为1
BULK_SIZE = 1

# 修改elasticsearch节点
NODES = [{"host": "192.168,1,240", "port": 9200}]

TASKS = [
    {
        "stream": {
            "database": "welian_commodity",  # 在此数据库执行sql语句
            "sql": "select * from commodity where modity_time >= ?",  # 将该sql语句选中的数据同步到 elasticsearch
            "seconds": 10,  # 每隔 seconds 秒同步一次,
            "init_time": "2018-08-29 15:00:00"  # 只有第一次同步会加载
        },
        "jobs": [
            {
                "pipeline": [
                    {"set_id": {"field": "id"}}  # 默认设置 id字段的值 为elasticsearch中的文档id
                ],
                "dest": {
                    "es": {
                        "action": "upsert",
                        "index": "test_index",   # 设置 index
                        "type": "test"          # 设置 type     
                    }
                }
            }
        ]
    }
]
```

**Comment by m358807551** [comment]
操作系统是啥？/etc/timezone

**Comment by m358807551** [comment]
/etc/timezone

**Comment by just3019** [comment]
Centos 7.5


原始邮件
发件人:m358807551notifications@github.com
收件人:m358807551/mysqlsmommysqlsmom@noreply.github.com
抄送:Johnny455674848@qq.com; Authorauthor@noreply.github.com
发送时间:2018年8月29日(周三) 17:17
主题:Re: [m358807551/mysqlsmom] 执行 python mysqlsmom.py config/example_cron.py 报错 (#5)


操作系统是啥？/etc/timezone

**Comment by m358807551** [comment]
操作系统是啥？
看下 /etc/timezone 这个文件夹里有啥
因为正常情况下 /etc/timezone 是个文件，里面的内容只有一行 Asia/Shanghai

**Comment by m358807551** [comment]
另外把下面这行删掉吧
`"password": "",  # 不需要密码则注释或删掉该行` 

再把下面的ip中的逗号改成点
`NODES = [{"host": "192.168,1,240", "port": 9200}]`

**Comment by just3019** [comment]
配置文件已经改过来了，
还是有问题额。是不是对系统版本有要求。



原始邮件
发件人:m358807551notifications@github.com
收件人:m358807551/mysqlsmommysqlsmom@noreply.github.com
抄送:Johnny455674848@qq.com; Authorauthor@noreply.github.com
发送时间:2018年8月29日(周三) 17:24
主题:Re: [m358807551/mysqlsmom] 执行 python mysqlsmom.py config/example_cron.py 报错 (#5)


另外把下面这行删掉吧
 "password": "", # 不需要密码则注释或删掉该行
再把下面的ip中的逗号改成点
 NODES = [{"host": "192.168,1,240", "port": 9200}]

**Comment by m358807551** [comment]
能看下 /etc/timezone 这个文件夹里面有什么嘛

**Comment by m358807551** [comment]
刚刚也个人加我，我以为他是你，所以两边说了半天 /etc/timezone 才搞明白误会了= =

**Comment by just3019** [comment]
啊哈哈，
就一个文件夹，什么都没有。


原始邮件
发件人:m358807551notifications@github.com
收件人:m358807551/mysqlsmommysqlsmom@noreply.github.com
抄送:Johnny455674848@qq.com; Authorauthor@noreply.github.com
发送时间:2018年8月29日(周三) 18:00
主题:Re: [m358807551/mysqlsmom] 执行 python mysqlsmom.py config/example_cron.py 报错 (#5)


刚刚也个人加我，我以为他是你，所以两边说了半天 /etc/timezone 才搞明白误会了= =

**Comment by m358807551** [comment]
这就好办了，把那个文件夹删了！

**Comment by just3019** [comment]
哇，原来是这个样子，太感谢了。

**Comment by m358807551** [comment]
好的，有其它问题欢迎讨论。
